version: '3.8'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  resource-postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${RESOURCE_DB_NAME}
    volumes:
      - ./init-scripts-resource:/docker-entrypoint-initdb.d

  song-postgres:
    image: postgres:17-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${SONG_DB_NAME}
    volumes:
      - ./init-scripts-song:/docker-entrypoint-initdb.d

  resource-service:
    build: ./resource-service
    depends_on:
      - resource-postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SONG_SERVICE_URL: ${SONG_SERVICE_URL}
      SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      RESOURCE_SERVICE_URI: lb://resource-service


  song-service:
    build: ./song-service
    depends_on:
      - song-postgres
      - resource-service
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8082
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SONG_SERVICE_URI: lb://song-service
    deploy:
      replicas: 2