version: '3.8'
services:
  resource-postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${RESOURCE_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts-resource:/docker-entrypoint-initdb.d

  song-postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${SONG_DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - ./init-scripts-song:/docker-entrypoint-initdb.d

  resource-service:
    build: ./resource-service
    ports:
      - "8080:8080"
    depends_on:
      - resource-postgres
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SONG_SERVICE_URL: ${SONG_SERVICE_URL}
      SERVER_PORT: ${APP_SERVER_PORT}

  song-service:
    build: ./song-service
    ports:
      - "8081:8080"
    depends_on:
      - song-postgres
      - resource-service
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${APP_SERVER_PORT}